### ISSUE TITLE
Clock button is never disabled

### ISSUE THREAD

**Issue by Zdro** [Dani3lSun/apex-plugin-clockpicker#8]
### Expected behavior
When we disable the item, the button to open the clock should be disabled as well

### Actual behavior
Only the input field is disabled

### Steps to reproduce the issue
1. Create a clock item on a page
2. Disable it with javascript 
  apex.item(id).disable

### APEX version (4.2.6 / 5.0.3)
5.0.3

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
Not relevant

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Not relevant

**Comment by Dani3lSun** [comment]
Hi @Zdro 

thanks for reporting this and also for providing nice a solution!

Atm I´m about to separate the PL/SQL and JavaScript parts of the plugin. This means all JavaScript logic will move to a separate file and the PL/SQL part only calls the main function from the file...

I think this would be a much nicer approach instead of the current one...

But this don´t have any effects on this topic, I will use your approach and will implement it in the JS file!

I hope I will manage to do it in the next 2 weeks...Next week is conference week and I don´t know if I can handle it until then...

Best wishes
Daniel
